#!/usr/bin/env python3
# from typing import *



# def solve(A: int, B: int) -> int:
def solve(A, B):
    ans = 0
    if A in [1,3,5,7] or B in [1,3,5,7]:
        ans += 1
    if A in [2,3,6,7] or B in [2,3,6,7]:
        ans += 2
    if A in [4,5,6,7] or B in [4,5,6,7]:
        ans += 4
    return ans
    

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B = map(int, input().split())
    a = solve(A, B)
    print(a)

if __name__ == '__main__':
    main()
