#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

constexpr int64_t MOD = 998244353;
auto solve(auto a, const std::vector<auto> &b, const std::vector<std::vector<auto> > &c, const std::vector<auto> &d, auto e) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto a, e;
    std::cin >> a;
    std::vector<auto> b(a);
    std::vector<std::vector<auto> > c(a, std::vector<auto>((a)));
    std::vector<auto> d(a);
    REP (i, a) {
        std::cin >> b[i];
        REP (j, i) {
            std::cin >> c[i][j];
        }
        std::cin >> d[i];
    }
    std::cin >> e;
    auto ans = solve(a, b, c, d, e);
    // failed to analyze output format
    // TODO: edit here
    std::cout << ans << '\n';
    return 0;
}
