#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, A: List[int], T: List[int], x: List[int], y: List[int]) -> Any:
def solve(N, Q, A, T, x, y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    A = [None for _ in range(N)]
    T = [None for _ in range(Q)]
    x = [None for _ in range(Q)]
    y = [None for _ in range(Q)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(Q):
        T[i] = int(next(tokens))
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, Q, A, T, x, y)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
