#!/usr/bin/env python3
# from typing import *



# def solve(S: List[str]) -> Tuple[int, int, int, int]:
def solve(S):
    a=b=c=d=0
    for i in range(10):
        for j in range(10):
            if S[i][j] == '#' and a == 0:
                a = i+1
                c = j+1
            if S[i][j] == '#' and b == 0:
                if i == 9 and j == 9:
                    b = i+1
                    d = j+1
                elif i == 9 and S[i][j+1] == '.':
                    b = i+1
                    d = j+1
                elif j == 9 and S[i+1][j] == '.':
                    b = i+1
                    d = j+1
                elif i != 9 and j != 9 and S[i+1][j] == '.' and S[i][j+1] == '.':
                    b = i+1
                    d = j+1
    return a,b,c,d


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = [None for _ in range(10)]
    for i in range(10):
        S[i] = input()
    A, B, C, D = solve(S)
    print(A, B)
    print(C, D)

if __name__ == '__main__':
    main()
