#!/usr/bin/env python3
# from typing import *



# def solve(X: int, Y: int, Z: int) -> int:
def solve(X, Y, Z):
    if Y < 0:
        X = -X
        Y = -Y
        Z = -Z
    if X < Y: return abs(X)
    else: 
        if Z > Y: return -1
        else: return abs(Z)+abs(X-Z)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y, Z = map(int, input().split())
    a = solve(X, Y, Z)
    print(a)

if __name__ == '__main__':
    main()
