#!/usr/bin/env python3
# from typing import *



# def solve(Y: int) -> int:
def solve(Y):
    for i in range(Y, 3003):
        if i % 4 == 2: return i

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Y = int(input())
    a = solve(Y)
    print(a)

if __name__ == '__main__':
    main()
