#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(std::string S, std::string T, int K, const std::vector<char> &C, const std::vector<std::string> &A) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    std::string S, T;
    int K;
    std::cin >> S >> T >> K;
    std::vector<char> C(K);
    std::vector<std::string> A(K);
    REP (i, K) {
        std::cin >> C[i] >> A[i];
    }
    auto ans = solve(S, T, K, C, A);
    std::cout << ans << '\n';
    return 0;
}
