#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

constexpr int64_t MOD = 998244353;
int64_t solve(int64_t N, int64_t M, int Q, const std::vector<int64_t> &L, const std::vector<int64_t> &R, const std::vector<int64_t> &X) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N, M;
    int Q;
    std::cin >> N >> M >> Q;
    std::vector<int64_t> L(Q), R(Q), X(Q);
    REP (i, Q) {
        std::cin >> L[i] >> R[i] >> X[i];
    }
    auto ans = solve(N, M, Q, L, R, X);
    std::cout << ans << '\n';
    return 0;
}
