#!/usr/bin/env python3
# from typing import *



# def solve(n: int, a: List[int]) -> int:
def solve(l1,r1,l2,r2):
    ans = 0
    for i in range(101):
        if l1 <= i < r1 and l2 <= i < r2:
            ans += 1
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    l1,r1,l2,r2 = map(int, input().split())
    a = solve(l1,r1,l2,r2)
    print(a)

if __name__ == '__main__':
    main()
