#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(x: "List[int]", y: "List[int]"):
    # 格子点でルート5の全列挙
    moves=[(1,2),(2,1),(-1,2),(-2,1),(1,-2),(2,-1),(-1,-2),(-2,-1)]
    # 点を全探索
    # x1からの距離の全列挙とx2からの全列挙が重なるかどうか見る
    for move1 in moves:
        for move2 in moves:
            if x[0]+move1[0]+move2[0]==x[1] and y[0]+move1[1]+move2[1]==y[1]:
                print(YES)
                exit()
    print(NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    x = [int()] * (2)  # type: "List[int]"
    y = [int()] * (2)  # type: "List[int]"
    for i in range(2):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
    solve(x, y)

if __name__ == '__main__':
    main()
