#!/usr/bin/env python3
# from typing import *



# def solve(R: int, C: int) -> str:
def solve(R, C):
    m = [[0 for _ in range(15)] for _ in range(15)]
    for i in range(15):
        for j in range(15):
            if i == 0 or i == 14 or j == 0 or j == 14:
                m[i][j] = 1
            elif (2 <= j <= 12 and (i == 2 or i == 12)) or (2 <= i <= 12 and (j == 2 or j == 12)):
                m[i][j] = 1
            elif (4 <= j <= 10 and (i == 4 or i == 10)) or (4 <= i <= 10 and (j == 4 or j == 10)):
                m[i][j] = 1
            elif (6 <= j <= 8 and (i == 6 or i == 8)) or (6 <= i <= 8 and (j == 6 or j == 8)):
                m[i][j] = 1
    return 'black' if m[R-1][C-1] == 1 else 'white'

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R, C = map(int, input().split())
    a = solve(R, C)
    print(a)

if __name__ == '__main__':
    main()
