#!/usr/bin/env python3
# from typing import *

from math import atan2, degrees


YES = 'Yes'
NO = 'No'

# def solve(n: int, a: List[int]) -> str:
def solve(A,B,C,D):
    a = degrees(atan2(D[1]-A[1], D[0]-A[0])) - degrees(atan2(B[1]-A[1], B[0]-A[0]))
    if a < 0: a += 360
    b = degrees(atan2(C[1]-B[1], C[0]-B[0])) - degrees(atan2(B[1]-A[1], B[0]-A[0]))
    if b < 0: b += 360
    c = degrees(atan2(D[1]-C[1], D[0]-C[0])) - degrees(atan2(C[1]-B[1], C[0]-B[0]))
    if c < 0: c += 360
    d = degrees(atan2(D[1]-C[1], D[0]-C[0])) - degrees(atan2(D[1]-A[1], D[0]-A[0]))
    if d < 0: d += 360
    return YES if a < 180 and b < 180 and c < 180 and d < 180 else NO

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    A,B,C,D = list(map(int, input().split())),list(map(int, input().split())),list(map(int, input().split())),list(map(int, input().split())), 
    a = solve(A,B,C,D)
    print(a)

if __name__ == '__main__':
    main()
