#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, X: int, T: int, D: int) -> int:
def solve(N, M, X, T, D):
    if M >= X: return T
    else:
        t = T - (X * D)
        for _ in range(M):
            t += D
        return t


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, X, T, D = map(int, input().split())
    a = solve(N, M, X, T, D)
    print(a)

if __name__ == '__main__':
    main()
