#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(X: int, A: int, D: int, N: int) -> int:
def solve(X, A, D, N):
    pass  # TODO: edit here
    first = A
    last = A+(N-1)*D
    # 公差を反転
    if D < 0:
        first, last = last, first
        D *= -1
    last -= first
    X-=first
    first=0
    if X <= 0 :
        return -X
    elif X >= last:
        return X - last
    else:
        return min(X%D, D-X%D)



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, A, D, N = map(int, input().split())
    a = solve(X, A, D, N)
    print(a)

if __name__ == '__main__':
    main()
