#!/usr/bin/env python3
# from typing import *



# def solve(N: str, A: List[List[str]]) -> str:
def solve(N, A):
    for i in range(N):
        for j in range(N):
            r = A[i][j]
            if r == '-': continue
            if r == 'W' and A[j][i] == 'L': continue 
            if r == 'L' and A[j][i] == 'W': continue 
            if r == 'D' and A[j][i] == 'D': continue 
            return 'incorrect'
    return 'correct'

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [list(input()) for _ in range(N)]
    a = solve(N, A)
    print(a)

if __name__ == '__main__':
    main()
