#!/usr/bin/env python3
import sys

MOD = 998244353  # type: int


def solve(N: int):
    ans = 0
    # 最大の桁まで回す
    for i in range(18):
        # 最大値 -> 桁の最大値か入力値
        top = min(10**(i+1)-1, N)
        # 最小値 -> 桁の最小値
        btm = 10**i
        # Nまで回す
        if btm > N: break
        #　最大値と最小値の差で和の公式
        cnt = top - btm + 1
        ans += ((cnt*(cnt+1)//2)%MOD)
        ans %= MOD
    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
