#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, T: List[int], X: List[int], Y: List[int], V: List[int]) -> Any:
def solve(N, Q, T, X, Y, V):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    Q = int(input())
    T = [None for _ in range(Q)]
    X = [None for _ in range(Q)]
    Y = [None for _ in range(Q)]
    V = [None for _ in range(Q)]
    for i in range(Q):
        T[i], X[i], Y[i], V[i] = map(int, input().split())
    ans = solve(N, Q, T, X, Y, V)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
