#!/usr/bin/env python3
# from typing import *

FIRST = 'First'
SECOND = 'Second'

# def solve(N: int, W: List[int], B: List[int]) -> str:
def solve(N, W, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    W = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        W[i] = int(next(tokens))
    for i in range(N):
        B[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, W, B)
    print(a)

if __name__ == '__main__':
    main()
