#!/usr/bin/env python3
# from typing import *
import collections


from itertools import permutations


# def solve(N: int, X: List[int], Y: List[int]) -> int:
def solve(N, X, Y):
    pass  # TODO: edit here
    ans = 0
    for i in range(N):
        for j in range(i+1, N):
            for k in range(j+1, N):
                if (X[k]-X[i])*(Y[j]-Y[i]) != (X[j]-X[i])*(Y[k]-Y[i]): 
                    ans += 1
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    X = [None for _ in range(N)]
    Y = [None for _ in range(N)]
    for i in range(N):
        X[i], Y[i] = map(int, input().split())
    a = solve(N, X, Y)
    print(a)

if __name__ == '__main__':
    main()
