#!/usr/bin/env python3
# from typing import *



# def solve(N: int, X: int) -> str:
def solve(N, X):
    return(('A'*N+'B'*N+'C'*N+'D'*N+'E'*N+'F'*N+'G'*N+'H'*N+'I'*N+'J'*N+'K'*N+'L'*N+'M'*N+'N'*N+'O'*N+'P'*N+'Q'*N+'R'*N+'S'*N+'T'*N+'U'*N+'V'*N+'W'*N+'X'*N+'Y'*N+'Z'*N)[X-1])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X = map(int, input().split())
    a = solve(N, X)
    print(a)

if __name__ == '__main__':
    main()
