#!/usr/bin/env python3
# from typing import *



# def solve(N: str, A: List[List[str]]) -> int:
def solve(N, A):
    ans = 0
    for i in range(N):
        for j in range(N):
            # 8方向
            for dx, dy in zip([-1, -1, -1, 0, 0, 1, 1, 1], [-1, 0, 1, 1, -1, 1, 0, -1]):
                t = ''
                # 初期値 + 方向 × ループ数
                for l in range(N):
                    x = (i + dx * l) % N
                    y = (j + dy * l) % N
                    t += str(A[x][y])
                ans = max(ans, int(t))
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [list(map(int, list(input()))) for _ in range(N)]
    r = solve(N, A)
    print(r)

if __name__ == '__main__':
    main()
