#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, x: List[int], y: List[int], q: List[int]) -> List[str]:
def solve(N, Q, x, y, q):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    q = [None for _ in range(Q)]
    for i in range(N):
        x[i], y[i] = map(int, input().split())
    for i in range(Q):
        q[i] = int(input())
    a = solve(N, Q, x, y, q)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
