#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(H: str, W: str, Q: str, q: List[str]) -> Any:
def solve(H, W, Q, q):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = input().split()
    Q = input()
    q = [None for _ in range(Q)]
    for i in range(Q):
        q[i] = input()
    ans = solve(H, W, Q, q)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
