#!/usr/bin/env python3
# from typing import *



# def solve(n: int, a: List[int]) -> int:
def solve(n, a):
    pass  # TODO: edit here
    ans = 0
    stack = [n-1]
    visited = [False]*n
    visited[-1] = True
    ans = 0
    while stack:
        now = stack.pop()
        t = a[now]
        ans += t[0]
        if t[1] == 0:
            continue
        for i in range(t[1]):
            tt = t[i+2]-1
            if not visited[tt]:
                visited[tt] = True
                stack.append(tt)
    return ans 

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    n = int(input())  # TODO: edit here
    a = [list(map(int, input().split())) for _ in range(n)]  # TODO: edit here
    a = solve(n, a)
    print(a)

if __name__ == '__main__':
    main()
