#!/usr/bin/env python3
# from typing import *



# def solve(N: int, S: int, T: int, A: int, B: int) -> float:
def solve(N, S, T, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, S, T, A, B = map(int, input().split())
    a = solve(N, S, T, A, B)
    print(a)

if __name__ == '__main__':
    main()
