#!/usr/bin/env python3
# from typing import *



# def solve(N: int, C: List[int], P: List[int], Q: int, L: List[int], R: List[int]) -> Tuple[List[str], List[str]]:
def solve(N, C, P, Q, L, R):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    C = [None for _ in range(N)]
    P = [None for _ in range(N)]
    for i in range(N):
        C[i], P[i] = map(int, input().split())
    Q = int(input())
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    for i in range(Q):
        L[i], R[i] = map(int, input().split())
    A, B = solve(N, C, P, Q, L, R)
    for i in range(Q):
        print(A[i], B[i])

if __name__ == '__main__':
    main()
