#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, T: int, AX: List[int], AY: List[int], BX: List[int], BY: List[int]) -> Tuple[str, List[str]]:
def solve(N, T, AX, AY, BX, BY):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, T = map(int, input().split())
    AX = [None for _ in range(N)]
    AY = [None for _ in range(N)]
    BX = [None for _ in range(N)]
    BY = [None for _ in range(N)]
    for i in range(N):
        AX[i], AY[i] = map(int, input().split())
    for i in range(N):
        BX[i], BY[i] = map(int, input().split())
    Yes, D = solve(N, T, AX, AY, BX, BY)
    print(Yes)
    print(*[D[i] for i in range(N)])

if __name__ == '__main__':
    main()
