#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


double solve(int N, int K, const std::vector<int64_t> &A, const std::vector<int64_t> &X, const std::vector<int64_t> &Y) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, K;
    std::cin >> N;
    std::vector<int64_t> X(N), Y(N);
    std::cin >> K;
    std::vector<int64_t> A(K);
    REP (i, K) {
        std::cin >> A[i];
    }
    REP (i, N) {
        std::cin >> X[i] >> Y[i];
    }
    auto ans = solve(N, K, A, X, Y);
    std::cout << ans << '\n';
    return 0;
}
