#!/usr/bin/env python3
# from typing import *



YES = 'Yes'
NO = 'No'

# def solve(N: int, X: List[int], Y: List[int], S: str) -> str:
def solve(N, X, Y, S):
    pass  # TODO: edit here
    ans = False
    l = dict()
    r = dict()
    for i in range(N):
        if S[i] == 'R':
            if Y[i] in r and r[Y[i]] >= X[i]:
                return "Yes"
        else:
            if Y[i] in l and l[Y[i]] <= X[i]:
                return "Yes"
        if S[i] == 'R':
            if Y[i] in l:
                l[Y[i]] = min(X[i], l[Y[i]])
            else:
                l[Y[i]] = X[i]
        else:
            if Y[i] in r:
                r[Y[i]] = max(X[i], r[Y[i]])
            else:
                r[Y[i]] = X[i]
    return "No"
        

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    X = [None for _ in range(N)]
    Y = [None for _ in range(N)]
    for i in range(N):
        X[i], Y[i] = map(int, input().split())
    S = input()
    a = solve(N, X, Y, S)
    print(a)

if __name__ == '__main__':
    main()
