#!/usr/bin/env python3
# from typing import *

smap = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

# def solve(S: str) -> int:
def solve(S):
    return 5 - smap.index(S)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)

if __name__ == '__main__':
    main()
