#!/usr/bin/env python3
# from typing import *



# def solve(n: int, a: List[int]) -> int:
def solve(r,c, a1,a2):
    pass  # TODO: edit here
    return (a1[c-1] if r == 1 else a2[c-1])

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    r,c = map(int, input().split())  # TODO: edit here
    a1 = list(map(int, input().split()))  # TODO: edit here
    a2 = list(map(int, input().split()))  # TODO: edit here
    a = solve(r,c, a1,a2)
    print(a)

if __name__ == '__main__':
    main()
