#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, int64_t M, const std::vector<std::string> &S, int Q, const std::vector<int64_t> &X, const std::vector<int64_t> &Y) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t M;
    int Q;
    std::cin >> N;
    std::vector<std::string> S(N);
    std::cin >> M;
    REP (i, N) {
        std::cin >> S[i];
    }
    std::cin >> Q;
    std::vector<int64_t> X(Q), Y(Q);
    REP (i, Q) {
        std::cin >> X[i] >> Y[i];
    }
    auto ans = solve(N, M, S, Q, X, Y);
    REP (i, Q) {
        std::cout << c[i] << '\n';
    }
    std::cout << d << '\n';
    return 0;
}
