#!/usr/bin/env python3
# from typing import *



# def solve(N: int, S: List[str]) -> List[str]:
def solve(N, O, S):
    for i in range(N):
        o = O[i]
        if S[o] == 0:
            print(o)
        else:
            print(o + '(' + str(S[o]) + ')')
        S[o] += 1

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    O = [input() for _ in range(N)]
    S = dict()
    for i in range(N):
        S[O[i]] = 0
    solve(N, O, S)

if __name__ == '__main__':
    main()
