#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(S: str) -> str:
def solve(S):
    S = '0'+S
    if S[1] != '0': return NO
    smap = [S[7]=='1',S[4]=='1',S[2]=='1' or S[8]=='1',S[5]=='1',S[3]=='1' or S[9]=='1',S[6]=='1',S[10]=='1']
    c = 0
    for s in smap:
        if c == 0 and s:
            c += 1
        elif c == 1 and not s:
            c += 1
        elif c == 2 and s:
            c += 1
    return YES if c == 3 else NO
 


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)

if __name__ == '__main__':
    main()
