#!/usr/bin/env python3
# from typing import *



# def solve(H: str, W: str, G: List[List[str]]) -> Tuple[str, str]:
def solve(H, W, G):
    i,j=0,0
    for _ in range(H*W):
        if G[i][j] == 'U' and i > 0: 
            i -= 1
        elif G[i][j] == 'D' and i < H-1: 
            i += 1
        elif G[i][j] == 'L' and j > 0: 
            j -= 1
        elif G[i][j] == 'R' and j < W-1: 
            j += 1
        else:
            print(i+1,j+1)
            exit()
    print(-1)
    exit()



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    G = [list(input()) for _ in range(H)]
    i, j = solve(H, W, G)
    print(i, j)

if __name__ == '__main__':
    main()
