#!/usr/bin/env python3
# from typing import *



# def solve(n: int, a: List[int]) -> int:
def solve(h1,h2,h3,w1,w2,w3):
    pass  # TODO: edit here
    l1,l2,l3 = [],[],[]
    for t in range(3):
        for i in range(1, 31):
            for j in range(1, 31):
                for k in range(1, 31):
                    if t == 0 and i+j+k == h1: l1.append([i,j,k])
                    if t == 1 and i+j+k == h2: l2.append([i,j,k])
                    if t == 2 and i+j+k == h3: l3.append([i,j,k])
    ans = 0
    for i in l1:
        for j in l2:
            for k in l3:
                if i[0]+j[0]+k[0] == w1 and i[1]+j[1]+k[1] == w2 and i[2]+j[2]+k[2] == w3:
                    ans += 1
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    
    h1,h2,h3,w1,w2,w3= map(int, input().split())
    a = solve(h1,h2,h3,w1,w2,w3)
    print(a)

if __name__ == '__main__':
    main()
