#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int N, const std::vector<int64_t> &d, const std::vector<int64_t> &u, const std::vector<int64_t> &v, const std::vector<int64_t> &w) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> d(N), u(N - 1), v(N - 1), w(N - 1);
    REP (i, N) {
        std::cin >> d[i];
    }
    REP (i, N - 1) {
        std::cin >> u[i] >> v[i] >> w[i];
    }
    auto ans = solve(N, d, u, v, w);
    std::cout << ans << '\n';
    return 0;
}
