#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, N: int, r: List[int], c: List[int], a: List[int]) -> List[str]:
def solve(H, W, N, r, c, a):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    r = [None for _ in range(N)]
    c = [None for _ in range(N)]
    a = [None for _ in range(N)]
    for i in range(N):
        r[i], c[i], a[i] = map(int, input().split())
    ans = solve(H, W, N, r, c, a)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
