#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, X: int, a: "List[int]", b: "List[int]"):
    dp=[[False]*(X+1) for _ in range(N+1)]
    dp[0][0] = True
    for i in range(N):
        for j in range(X+1):
            if not dp[i][j]: continue
            if j+a[i] <= X: 
                dp[i+1][j+a[i]] = True
            if j+b[i] <= X: 
                dp[i+1][j+b[i]] = True
    print(YES if dp[-1][-1] else NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    a = [int()] * (N)  # type: "List[int]"
    b = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    solve(N, X, a, b)

if __name__ == '__main__':
    main()
