#!/usr/bin/env python3
# from typing import *



# def solve(N: int, a: List[int]) -> int:
def solve(N, a):
    ans = 0
    t = 0
    a = [0]+a
    # ai=i and aj=j -> ak=k の個数 
    for i in range(1, N+1):
        if a[i]==i:
            t+=1
    # 組み合わせはkC2、つまり和の公式
    ans += t*(t-1)//2
    # aj=i and ai=j の個数
    for i in range(1, N+1):
        j=a[i]
        if i<j and a[j]==i:
            ans += 1
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(N, a)
    print(a1)

if __name__ == '__main__':
    main()
