#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    S = [None for _ in range(N - 1)]
    M = random.randint(1, 1000)  # TODO: edit here
    X = [None for _ in range(M)]
    for i in range(N - 1):
        S[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(M):
        X[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, M)
    print(*[S[i] for i in range(N - 1)])
    print(*[X[i] for i in range(M)])

if __name__ == "__main__":
    main()
