#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    M = random.randint(1, 10 ** 9)  # TODO: edit here
    E = random.randint(1, 1000)  # TODO: edit here
    U = [None for _ in range(E)]
    V = [None for _ in range(E)]
    for i in range(E):
        U[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        V[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    X = [None for _ in range(Q)]
    for i in range(Q):
        X[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, M, E)
    for i in range(E):
        print(U[i], V[i])
    print(Q)
    for i in range(Q):
        print(X[i])

if __name__ == "__main__":
    main()
