#!/usr/bin/env python3
# from typing import *

MOD = 1000000007

# def solve(N: int, Q: int, x: List[int], y: List[int], z: List[int], w: List[int]) -> int:
def solve(N, Q, x, y, z, w):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    x = [None for _ in range(Q)]
    y = [None for _ in range(Q)]
    z = [None for _ in range(Q)]
    w = [None for _ in range(Q)]
    for i in range(Q):
        x[i], y[i], z[i], w[i] = map(int, input().split())
    a = solve(N, Q, x, y, z, w)
    print(a)

if __name__ == '__main__':
    main()
