#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(R: int, G: int, B: int, K: int, X: int, Y: int, Z: int) -> int:
def solve(R, G, B, K, X, Y, Z):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R, G, B, K = map(int, input().split())
    X, Y, Z = map(int, input().split())
    a = solve(R, G, B, K, X, Y, Z)
    print(a)

if __name__ == '__main__':
    main()
