#!/usr/bin/env python3
# from typing import *

def check(s):
    for i in range(len(s)//2):
        if s[i] == '(' and s[len(s)-i-1] == ')':
            continue
        else:
            return False
    return True

# def solve(N: int) -> Any:
def solve(N):
    ans = []
    for i in range(1<<N):
        t = ""
        c = 0
        for j in range(N):
            if i >> j & 1:
                t += '('
                c += 1
            else:
                t += ')'
                c -= 1
            # 閉じカッコのほうが多くなった時点でNG
            if c < 0:
                break
        if c == 0:
            ans.append(t)
    for a in sorted(ans):
        print(a)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    ans = solve(N)

if __name__ == '__main__':
    main()
