x1,y1 = map(int, input().split())
x2,y2 = map(int, input().split())
x3,y3 = map(int, input().split())
ans = []
if x1 == x2: ans.append(x3)
if x2 == x3: ans.append(x1)
if x1 == x3: ans.append(x2)
if y1 == y2: ans.append(y3)
if y2 == y3: ans.append(y1)
if y1 == y3: ans.append(y2)
print(*ans)