#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, Q: int, X: List[int], Y: List[int], A: List[int], B: List[int]) -> List[str]:
def solve(N, M, Q, X, Y, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, Q = map(int, input().split())
    X = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(M):
        X[i], Y[i] = map(int, input().split())
    for i in range(Q):
        A[i], B[i] = map(int, input().split())
    a = solve(N, M, Q, X, Y, A, B)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
