#!/usr/bin/env python3
# from typing import *



# def solve(N: int, P: int, Q: int, A: List[int]) -> int:
def solve(N, P, Q, A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    P = int(next(tokens))
    Q = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, P, Q, A)
    print(a)

if __name__ == '__main__':
    main()
