#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, A: List[int], X: List[int], Y: List[int]) -> Tuple[int, List[int], int, List[int]]:
def solve(N, Q, A, X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    A = [None for _ in range(N)]
    X = [None for _ in range(Q)]
    Y = [None for _ in range(Q)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(Q):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    assert next(tokens, None) is None
    x, B, y, C = solve(N, Q, A, X, Y)
    print(x)
    print(*[B[i] for i in range(x)])
    print(y)
    print(*[C[i] for i in range(y)])

if __name__ == '__main__':
    main()
