#!/usr/bin/env python3
# from typing import *

from collections import defaultdict


YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, T: int, A: List[int], X: List[int], Y: List[int]) -> str:
def solve(N, M, T, A, xy):
    ans = True
    for i in range(1, N):
        if T <= A[i]: ans = False
        T -= A[i]
        T += xy[i+1]
    return YES if ans else NO

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    T = int(next(tokens))
    A = [0]+[None for _ in range(N - 1)]
    xy = [0]*(N+1)
    for i in range(1, N):
        A[i] = int(next(tokens))
    for i in range(M):
        x = int(next(tokens))
        y = int(next(tokens))
        xy[x] = y
    assert next(tokens, None) is None
    b = solve(N, M, T, A, xy)
    print(b)

if __name__ == '__main__':
    main()
