#!/usr/bin/env python3
# from typing import *

# def solve(a: int, b: int, c: List[str], d: List[int], e: int) -> Any:
def solve():
    n,q = map(int, input().split())
    a = input()
    p = 0
    for _ in range(q):
        t,x = map(int, input().split())
        if t == 1:
            p += x
        else:
            print(a[x-1-p%n])
    
# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    ans = solve()

if __name__ == '__main__':
    main()
